module radiation_mod
!==================================================================================
! Radiative transfer lookup tables for HEXTOR.
!
! Provides OLR and top-of-atmosphere (planetary) albedo by interpolation in
! precomputed tables indexed by
!
!     dry surface pressure  x  CO2 mixing ratio  x  CH4 mixing ratio
!                           x  surface temperature
!     ( x  solar zenith angle  x  surface albedo, for the albedo table )
!
! Three on-disk formats are supported and detected automatically:
!
!   v3 (pressure- and CH4-resolved).  As v2, with a '/ch4' axis vector and one
!   extra dimension on both data arrays.  Generated by
!   tools/make_radiation_table.py --ch4-axis.
!
!   v2 (pressure-resolved).  The HDF5 file carries rank-3 '/olr' and rank-5
!   '/palb' datasets plus explicit axis vectors '/pressure', '/fco2',
!   '/temperature', '/zenith' and '/surfalb'.  Grid dimensions are read from
!   the file, so the table may be regridded without recompiling HEXTOR.
!   Generated by tools/make_radiation_table.py from ExoColumn/ExoRT.  Loaded
!   with a single CH4 level, so v2 and v3 share one code path; the fch4
!   argument is then clamped away exactly as pdry is for v1.
!
!   v1 (legacy, 1 bar).  The original flat row-per-sample '/olr' (4 columns)
!   and '/palb' (6 columns) datasets on a fixed 92 x 19 (x 4 x 5) grid, which
!   assume 1 bar of N2 background.  These are read into the same arrays with a
!   single pressure level at 1 bar, so every downstream code path is identical;
!   the pressure argument is then simply ignored (the bracket clamps).
!
! Axis conventions
!   pressure   dry surface pressure pN2 + pCO2 [bar]; interpolated in log10
!   fco2       CO2 mixing ratio pCO2/p_dry [-];       interpolated in log10
!   ch4        CH4 mixing ratio pCH4/p_dry [-];       interpolated in log10.
!              The axis has a nonzero floor (the generator uses 1e-8) rather
!              than a zero level, so that the log interpolation is well posed;
!              fch4 = 0 clamps to that floor, which is radiatively
!              indistinguishable from CH4-free (measured: 0.08 W/m^2 in OLR and
!              1e-4 in albedo at 1 bar, 400 ppm CO2, 280 K).
!   temperature surface temperature [K];              interpolated linearly,
!              extrapolated outside the table by a fitted power law (below)
!   zenith     solar zenith angle [degrees];          interpolated linearly
!   surfalb    broadband surface albedo [-];          interpolated linearly
!
! Array index order is the REVERSE of the axis order above, so that the
! fastest-varying axis is innermost in Fortran storage.  The HDF5 datasets are
! written in the natural axis order, which the HDF5 Fortran interface maps onto
! the reversed Fortran declaration automatically:
!
!     HDF5 '/olr'  (npre, nco2, nch4, ntmp)
!                                    <->  olr_table (ntmp, nch4, nco2, npre)
!     HDF5 '/palb' (npre, nco2, nch4, ntmp, nzen, nsab)
!                          <->  palb_table (nsab, nzen, ntmp, nch4, nco2, npre)
!
! A v2 file omits the CH4 axis from both datasets; the reader inserts a single
! CH4 level so the in-memory shapes above always hold.
!
! OLR UNITS.  Both formats store OLR in mW/m^2 (i.e. W/m^2 x 1000), which is
! the historical convention of the v1 tables: driver.f divides the returned
! value by 1000 to get W/m^2.  A v2 table must therefore be written in the same
! units — tools/make_radiation_table.py does this.  The v1 files additionally
! store the value negated; the reader flips the sign at load so that
! olr_table is always a positive flux and the rest of the module never has to
! care which format it came from.
!==================================================================================

  use hdf5

!==================================================================================
implicit none

public  :: radiation_init, radiation_end, getOLR, getPALB
public  :: radiation_nch4, radiation_ch4_range
private :: bracket, read_table_v2, read_table_v1, fit_extrap_exponents
!==================================================================================

  ! ---- v1 (legacy) fixed grid -----------------------------------------------
  integer, parameter :: nolr_v1 = 4
  integer, parameter :: nalb_v1 = 6
  integer, parameter :: dolr_v1 = 1748
  integer, parameter :: dalb_v1 = 34960
  integer, parameter :: nco2_v1 = 92
  integer, parameter :: ntmp_v1 = 19

  ! ---- Grid dimensions (set at init from the file) --------------------------
  integer :: npre, nco2, nch4, ntmp, nzen, nsab

  ! Whether the file actually carried a '/ch4' axis.  Distinct from nch4 == 1,
  ! which is also what a genuine single-level CH4 axis gives.
  logical :: table_has_ch4 = .false.

  character*100 :: sds_olr = "/olr"
  character*100 :: sds_alb = "/palb"
  integer(HID_T):: file_id
  integer       :: status

  ! ---- Axis levels ----------------------------------------------------------
  real, allocatable, dimension(:) :: prelevels   ! dry surface pressure [bar]
  real, allocatable, dimension(:) :: fco2levels  ! CO2 mixing ratio [-]
  real, allocatable, dimension(:) :: ch4levels   ! CH4 mixing ratio [-]
  real, allocatable, dimension(:) :: templevels  ! surface temperature [K]
  real, allocatable, dimension(:) :: zenilevels  ! solar zenith angle [deg]
  real, allocatable, dimension(:) :: albelevels  ! surface albedo [-]

  ! ---- Tables (see index-order note in the header) --------------------------
  real, allocatable :: olr_table(:,:,:,:)      ! (ntmp, nch4, nco2, npre)
  real, allocatable :: palb_table(:,:,:,:,:,:) ! (nsab,nzen,ntmp,nch4,nco2,npre)

  ! Effective OLR power-law exponents at the upper and lower temperature
  ! boundaries, fitted per (pressure, CO2, CH4) column from the last/first two
  ! temperature levels so that extrapolation follows the actual table gradient
  ! rather than assuming T^4.
  real, allocatable :: n_eff_upper(:,:,:)      ! (nch4, nco2, npre)
  real, allocatable :: n_eff_lower(:,:,:)      ! (nch4, nco2, npre)

contains

!==================================================================================

subroutine radiation_init( radfile )

  character*(*), intent(in) :: radfile

  integer :: error
  logical :: has_pressure

  call h5open_f( status )
  call h5fopen_f( radfile, H5F_ACC_RDONLY_F, file_id, status )
  if ( status .ne. 0 ) then
    write(*,*) "radiation_init: cannot open HDF5 file: ", trim(radfile)
    stop
  end if

  ! Format detection: only the pressure-resolved tables carry a '/pressure'
  ! axis dataset.
  call h5lexists_f( file_id, "/pressure", has_pressure, error )
  if ( error .ne. 0 ) has_pressure = .false.

  if ( has_pressure ) then
    call read_table_v2()
  else
    call read_table_v1()
  end if

  call h5fclose_f( file_id, error )
  call h5close_f( status )

  call fit_extrap_exponents()

  write(*,'(a,a)')    " radiation_init: ", trim(radfile)
  write(*,'(a,i0,a,i0,a,i0,a,i0,a,i0,a,i0)')                                &
       "   grid: npre=", npre, " nco2=", nco2, " nch4=", nch4,              &
       " ntmp=", ntmp, " nzen=", nzen, " nsab=", nsab
  write(*,'(a,es10.3,a,es10.3,a)')                                          &
       "   p_dry  [bar]: ", prelevels(1),  " .. ", prelevels(npre)
  write(*,'(a,es10.3,a,es10.3)')                                            &
       "   fco2        : ", fco2levels(1), " .. ", fco2levels(nco2)
  if ( table_has_ch4 ) then
    write(*,'(a,es10.3,a,es10.3,a,i0,a)')                                   &
       "   fch4        : ", ch4levels(1),  " .. ", ch4levels(nch4),         &
       " (", nch4, " levels)"
  else
    write(*,'(a)') "   fch4        : none (table has no CH4 axis)"
  end if
  write(*,'(a,f7.1,a,f7.1)')                                                &
       "   T      [K]  : ", templevels(1), " .. ", templevels(ntmp)
  write(*,'(a,f6.2,a,f6.2)')                                                &
       "   surfalb     : ", albelevels(1), " .. ", albelevels(nsab)

  return

end subroutine radiation_init

!==================================================================================

! Number of CH4 levels in the loaded table, or 0 if the file carried no CH4
! axis at all.  Exposed so that a caller asking for CH4 can refuse a table
! that would silently clamp it away -- see the check after radiation_init in
! driver.f.
integer function radiation_nch4()

  if ( table_has_ch4 ) then
    radiation_nch4 = nch4
  else
    radiation_nch4 = 0
  end if

end function radiation_nch4

!==================================================================================

! Range spanned by the table's CH4 axis.  A request outside it is clamped by
! bracket(), which for CH4 would quietly model a different atmosphere than the
! namelist asked for, so callers should check rather than rely on the clamp.
subroutine radiation_ch4_range( lo, hi )

  real, intent(out) :: lo, hi

  if ( table_has_ch4 ) then
    lo = ch4levels(1)
    hi = ch4levels(nch4)
  else
    lo = 0.0
    hi = 0.0
  end if

end subroutine radiation_ch4_range

!==================================================================================

subroutine read_table_v2

! Pressure-resolved table: dimensions and axes come from the file.

  integer(HID_T)   :: dset_id, space_id
  integer(HSIZE_T) :: dims6(6), maxdims6(6)
  integer(HSIZE_T) :: dims4(4)
  integer(HSIZE_T) :: dims1(1)
  integer          :: error, rank
  logical          :: has_ch4

  ! Grid dimensions are taken from the albedo dataset, which carries every
  ! axis.  Note h5sget_simple_extent_dims_f reports the dataspace in Fortran
  ! (reversed) order, matching the array declarations.  A v3 table adds the
  ! CH4 axis, making /palb rank 6 instead of rank 5.
  call h5lexists_f( file_id, "/ch4", has_ch4, error )
  if ( error .ne. 0 ) has_ch4 = .false.
  table_has_ch4 = has_ch4

  call h5dopen_f( file_id, sds_alb, dset_id, error )
  call h5dget_space_f( dset_id, space_id, error )
  call h5sget_simple_extent_ndims_f( space_id, rank, error )
  if ( rank .ne. merge(6, 5, has_ch4) ) then
    write(*,*) "radiation_init: /palb rank ", rank, " does not match the ",  &
               "presence of a /ch4 axis (", has_ch4, ")"
    stop
  end if
  call h5sget_simple_extent_dims_f( space_id, dims6, maxdims6, error )
  call h5sclose_f( space_id, error )

  nsab = int(dims6(1))
  nzen = int(dims6(2))
  ntmp = int(dims6(3))
  if ( has_ch4 ) then
    nch4 = int(dims6(4))
    nco2 = int(dims6(5))
    npre = int(dims6(6))
  else
    nch4 = 1
    nco2 = int(dims6(4))
    npre = int(dims6(5))
  end if

  allocate( prelevels(npre), fco2levels(nco2), templevels(ntmp) )
  allocate( ch4levels(nch4) )
  allocate( zenilevels(nzen), albelevels(nsab) )
  allocate( olr_table(ntmp, nch4, nco2, npre) )
  allocate( palb_table(nsab, nzen, ntmp, nch4, nco2, npre) )

  ! With nch4 = 1 the in-memory array has exactly the element count and
  ! ordering of the rank-5 v2 dataset, so the same read fills it.
  dims6 = (/ int(nsab,HSIZE_T), int(nzen,HSIZE_T), int(ntmp,HSIZE_T),       &
             int(nch4,HSIZE_T), int(nco2,HSIZE_T), int(npre,HSIZE_T) /)
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, palb_table, dims6, error )
  call h5dclose_f( dset_id, error )

  dims4 = (/ int(ntmp,HSIZE_T), int(nch4,HSIZE_T), int(nco2,HSIZE_T),       &
             int(npre,HSIZE_T) /)
  call h5dopen_f( file_id, sds_olr, dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, olr_table, dims4, error )
  call h5dclose_f( dset_id, error )

  dims1 = (/ int(npre,HSIZE_T) /)
  call h5dopen_f( file_id, "/pressure", dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, prelevels, dims1, error )
  call h5dclose_f( dset_id, error )

  dims1 = (/ int(nco2,HSIZE_T) /)
  call h5dopen_f( file_id, "/fco2", dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, fco2levels, dims1, error )
  call h5dclose_f( dset_id, error )

  dims1 = (/ int(ntmp,HSIZE_T) /)
  call h5dopen_f( file_id, "/temperature", dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, templevels, dims1, error )
  call h5dclose_f( dset_id, error )

  dims1 = (/ int(nzen,HSIZE_T) /)
  call h5dopen_f( file_id, "/zenith", dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, zenilevels, dims1, error )
  call h5dclose_f( dset_id, error )

  dims1 = (/ int(nsab,HSIZE_T) /)
  call h5dopen_f( file_id, "/surfalb", dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, albelevels, dims1, error )
  call h5dclose_f( dset_id, error )

  if ( has_ch4 ) then
    dims1 = (/ int(nch4,HSIZE_T) /)
    call h5dopen_f( file_id, "/ch4", dset_id, error )
    call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, ch4levels, dims1, error )
    call h5dclose_f( dset_id, error )
  else
    ! A single degenerate level: bracket() clamps to it and axfrac() returns 0
    ! for a degenerate bracket, so the CH4 axis contributes nothing and its
    ! log10 is never evaluated.
    ch4levels = (/ 0.0 /)
  end if

  return

end subroutine read_table_v2

!==================================================================================

subroutine read_table_v1

! Legacy 1 bar table: flat row-per-sample datasets on the historical fixed
! grid.  Loaded into the same rank-3 / rank-5 arrays with a single pressure
! level so that getOLR and getPALB have only one code path.

  integer(HID_T)   :: dset_id
  integer(HSIZE_T) :: dims_olr(2), dims_alb(2)
  integer          :: error, i, j, ico2, itmp, izen, ialb
  real, allocatable :: database_olr(:,:)
  real, allocatable :: database_alb(:,:)

  npre = 1
  nco2 = nco2_v1
  nch4 = 1
  table_has_ch4 = .false.
  ntmp = ntmp_v1
  nzen = 4
  nsab = 5

  allocate( prelevels(npre), fco2levels(nco2), templevels(ntmp) )
  allocate( ch4levels(nch4) )
  allocate( zenilevels(nzen), albelevels(nsab) )
  allocate( olr_table(ntmp, nch4, nco2, npre) )
  allocate( palb_table(nsab, nzen, ntmp, nch4, nco2, npre) )

  allocate( database_olr(nolr_v1, dolr_v1) )
  allocate( database_alb(nalb_v1, dalb_v1) )
  dims_olr = (/ int(nolr_v1,HSIZE_T), int(dolr_v1,HSIZE_T) /)
  dims_alb = (/ int(nalb_v1,HSIZE_T), int(dalb_v1,HSIZE_T) /)

  call h5dopen_f( file_id, sds_olr, dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, database_olr, dims_olr, error )
  call h5dclose_f( dset_id, error )

  call h5dopen_f( file_id, sds_alb, dset_id, error )
  call h5dread_f( dset_id, H5T_NATIVE_DOUBLE, database_alb, dims_alb, error )
  call h5dclose_f( dset_id, error )

  ! The legacy tables were computed for 1 bar of N2 background.
  prelevels  = (/ 1.0 /)
  ch4levels  = (/ 0.0 /)
  fco2levels = database_olr(2, :nco2)
  templevels = database_olr(3, ::nco2)
  zenilevels = (/ 0., 30., 60., 90. /)
  albelevels = (/ 0.2, 0.4, 0.6, 0.8, 1.0 /)

  ! OLR: CO2 is the inner loop, T the outer, in the flat data.  Stored negated
  ! on disk; flip to a positive flux here.
  do j = 1, ntmp
    do i = 1, nco2
      olr_table(j, 1, i, 1) = -database_olr(4, (j-1)*nco2 + i)
    end do
  end do

  ! PALB: row ordering in the flat data is not guaranteed, so map each row onto
  ! the grid via its own axis values.
  do i = 1, dalb_v1
    ico2 = minloc( abs( fco2levels - database_alb(2,i) ), 1 )
    itmp = minloc( abs( templevels - database_alb(3,i) ), 1 )
    izen = minloc( abs( zenilevels - database_alb(4,i) ), 1 )
    ialb = minloc( abs( albelevels - database_alb(5,i) ), 1 )
    palb_table(ialb, izen, itmp, 1, ico2, 1) = database_alb(6,i)
  end do

  deallocate( database_olr )
  deallocate( database_alb )

  return

end subroutine read_table_v1

!==================================================================================

subroutine fit_extrap_exponents

! OLR outside the tabulated temperature range is extrapolated as a power law
! olr * (T/T_edge)**n_eff, with n_eff fitted from the gradient at the table
! boundary for each (CO2, CH4, pressure) column.  This is not a T^4 law: for
! the 1 bar Sun table n_eff_upper ~ 2.35 and n_eff_lower ~ 3.77.
!
! The upper exponent is floored at zero.  When the top of the table lies on
! the runaway plateau -- where OLR has saturated and wobbles by ~1 W/m^2 either
! way -- the fitted exponent can come out slightly negative, and extrapolating
! that means OLR FALLS as the model heats: an unbounded positive feedback that
! sends an EBM to absurd temperatures and then to NaN.  A flat extrapolation is
! also the better physics, since above the plateau OLR stays near the runaway
! limit until the near-infrared windows open at far higher temperatures
! (Goldblatt et al. 2013).  Note this does NOT manufacture a stabilising
! feedback: a case whose absorbed flux exceeds the runaway limit still has no
! equilibrium, and should be reported as a runaway rather than as a climate.

  integer :: i, j, k

  ! A freshly generated table can carry a failed grid point as a non-finite
  ! value, and the fit below would turn that into a silent NaN exponent that
  ! only shows up later as strange climate.  Refuse the table instead.
  if ( any( olr_table  .ne. olr_table  ) .or. any( olr_table .le. 0.0 ) .or.  &
       any( palb_table .ne. palb_table ) ) then
    write(*,*) "radiation_init: table contains non-finite or non-positive ", &
               "values -- check it with tools/check_table_sanity.py"
    stop
  end if

  allocate( n_eff_upper(nch4, nco2, npre) )
  allocate( n_eff_lower(nch4, nco2, npre) )

  do k = 1, npre
    do i = 1, nco2
      do j = 1, nch4
        n_eff_upper(j,i,k) =                                                  &
              log( olr_table(ntmp,j,i,k) / olr_table(ntmp-1,j,i,k) )          &
            / log( templevels(ntmp)      / templevels(ntmp-1)      )
        n_eff_upper(j,i,k) = max( n_eff_upper(j,i,k), 0.0 )
        n_eff_lower(j,i,k) =                                                  &
              log( olr_table(2,j,i,k)    / olr_table(1,j,i,k)      )          &
            / log( templevels(2)         / templevels(1)           )
      end do
    end do
  end do

  return

end subroutine fit_extrap_exponents

!==================================================================================

! Find bracketing indices in a sorted array such that levels(lo) <= val < levels(hi).
! Clamps: returns lo=hi=1 if val <= levels(1), lo=hi=n if val >= levels(n).
subroutine bracket( levels, n, val, lo, hi )

  integer, intent(in)  :: n
  real,    intent(in)  :: levels(n), val
  integer, intent(out) :: lo, hi
  integer :: i

  if ( val .le. levels(1) ) then
    lo = 1
    hi = 1
  else if ( val .ge. levels(n) ) then
    lo = n
    hi = n
  else
    lo = 1
    do i = 1, n - 1
      if ( levels(i) .le. val .and. val .lt. levels(i+1) ) then
        lo = i
        exit
      end if
    end do
    hi = lo + 1
  end if

end subroutine bracket

!==================================================================================

! Interpolation weight along one axis.  Returns 0 for a clamped (degenerate)
! bracket, and interpolates in log10 when logaxis is set.
real function axfrac( levels, lo, hi, val, logaxis )

  real,    intent(in) :: levels(:)
  integer, intent(in) :: lo, hi
  real,    intent(in) :: val
  logical, intent(in) :: logaxis

  if ( lo .eq. hi ) then
    axfrac = 0.0
  else if ( logaxis ) then
    axfrac = ( log10(val)         - log10(levels(lo)) )                       &
           / ( log10(levels(hi))  - log10(levels(lo)) )
  else
    axfrac = ( val - levels(lo) ) / ( levels(hi) - levels(lo) )
  end if

end function axfrac

!==================================================================================

subroutine getOLR( pdry, fco2, fch4, tg0, olr )

! Outgoing longwave radiation [mW/m^2 — see the units note in the module
! header] for dry surface pressure pdry [bar], CO2 mixing ratio fco2, CH4
! mixing ratio fch4 and surface temperature tg0 [K].
!
! Against a table with no CH4 axis, fch4 is clamped away (nch4 = 1 gives a
! degenerate bracket and a zero axis weight).  Callers that mean to model CH4
! should check radiation_nch4() once at startup rather than discover it here.

  real, intent(in)  :: pdry
  real, intent(in)  :: fco2
  real, intent(in)  :: fch4
  real, intent(in)  :: tg0
  real, intent(out) :: olr

  integer :: prelo, prehi, co2lo, co2hi, ch4lo, ch4hi, tmplo, tmphi
  integer :: ip, ic, im, it
  real    :: prefrac, co2frac, ch4frac, tmpfrac
  real    :: tg0_eval, n_eff, w

  ! Clamp T to the table range for the interpolation itself; the power-law
  ! correction below carries it the rest of the way.
  tg0_eval = max( templevels(1), min( templevels(ntmp), tg0 ) )

  call bracket( prelevels, npre, pdry,     prelo, prehi )
  call bracket( fco2levels, nco2, fco2,    co2lo, co2hi )
  call bracket( ch4levels, nch4, fch4,     ch4lo, ch4hi )
  call bracket( templevels, ntmp, tg0_eval, tmplo, tmphi )

  prefrac = axfrac( prelevels,  prelo, prehi, pdry,     .true.  )
  co2frac = axfrac( fco2levels, co2lo, co2hi, fco2,     .true.  )
  ch4frac = axfrac( ch4levels,  ch4lo, ch4hi, fch4,     .true.  )
  tmpfrac = axfrac( templevels, tmplo, tmphi, tg0_eval, .false. )

  ! Quadrilinear interpolation as a weighted sum over the 16 corners.
  olr = 0.0
  do ip = 0, 1
    do ic = 0, 1
      do im = 0, 1
        do it = 0, 1
          w = ( merge(prefrac, 1.0-prefrac, ip .eq. 1) )                      &
            * ( merge(co2frac, 1.0-co2frac, ic .eq. 1) )                      &
            * ( merge(ch4frac, 1.0-ch4frac, im .eq. 1) )                      &
            * ( merge(tmpfrac, 1.0-tmpfrac, it .eq. 1) )
          if ( w .eq. 0.0 ) cycle
          olr = olr + w * olr_table( merge(tmphi,tmplo,it .eq. 1),            &
                                     merge(ch4hi,ch4lo,im .eq. 1),            &
                                     merge(co2hi,co2lo,ic .eq. 1),            &
                                     merge(prehi,prelo,ip .eq. 1) )
        end do
      end do
    end do
  end do

  if ( tg0 .lt. templevels(1) .or. tg0 .gt. templevels(ntmp) ) then
    ! Blend the fitted exponent over the 8 (pressure, CO2, CH4) corners.
    n_eff = 0.0
    do ip = 0, 1
      do ic = 0, 1
        do im = 0, 1
          w = ( merge(prefrac, 1.0-prefrac, ip .eq. 1) )                      &
            * ( merge(co2frac, 1.0-co2frac, ic .eq. 1) )                      &
            * ( merge(ch4frac, 1.0-ch4frac, im .eq. 1) )
          if ( w .eq. 0.0 ) cycle
          if ( tg0 .gt. templevels(ntmp) ) then
            n_eff = n_eff + w * n_eff_upper( merge(ch4hi,ch4lo,im .eq. 1),    &
                                             merge(co2hi,co2lo,ic .eq. 1),    &
                                             merge(prehi,prelo,ip .eq. 1) )
          else
            n_eff = n_eff + w * n_eff_lower( merge(ch4hi,ch4lo,im .eq. 1),    &
                                             merge(co2hi,co2lo,ic .eq. 1),    &
                                             merge(prehi,prelo,ip .eq. 1) )
          end if
        end do
      end do
    end do
    olr = olr * ( tg0 / tg0_eval )**n_eff
  end if

  return

end subroutine getOLR

!==================================================================================

subroutine getPALB( pdry, fco2, fch4, tg0, zy, surfalb, palb )

! Planetary (top-of-atmosphere) albedo for dry surface pressure pdry [bar],
! CO2 mixing ratio fco2, CH4 mixing ratio fch4, surface temperature tg0 [K],
! solar zenith angle zy [degrees] and broadband surface albedo surfalb.

  real, intent(in)  :: pdry
  real, intent(in)  :: fco2
  real, intent(in)  :: fch4
  real, intent(in)  :: tg0
  real, intent(in)  :: zy
  real, intent(in)  :: surfalb
  real, intent(out) :: palb

  integer :: prelo, prehi, co2lo, co2hi, ch4lo, ch4hi
  integer :: tmplo, tmphi, zenlo, zenhi, alblo, albhi
  integer :: ip, ic, im, it, iz, ia
  real    :: prefrac, co2frac, ch4frac, tmpfrac, zenfrac, albfrac
  real    :: w

  call bracket( prelevels,  npre, pdry,    prelo, prehi )
  call bracket( fco2levels, nco2, fco2,    co2lo, co2hi )
  call bracket( ch4levels,  nch4, fch4,    ch4lo, ch4hi )
  call bracket( templevels, ntmp, tg0,     tmplo, tmphi )
  call bracket( zenilevels, nzen, zy,      zenlo, zenhi )
  call bracket( albelevels, nsab, surfalb, alblo, albhi )

  prefrac = axfrac( prelevels,  prelo, prehi, pdry,    .true.  )
  co2frac = axfrac( fco2levels, co2lo, co2hi, fco2,    .true.  )
  ch4frac = axfrac( ch4levels,  ch4lo, ch4hi, fch4,    .true.  )
  tmpfrac = axfrac( templevels, tmplo, tmphi, tg0,     .false. )
  zenfrac = axfrac( zenilevels, zenlo, zenhi, zy,      .false. )
  albfrac = axfrac( albelevels, alblo, albhi, surfalb, .false. )

  ! Hexalinear interpolation as a weighted sum over the 64 corners.  A CH4
  ! value sitting exactly on a table node -- the usual case for a run holding
  ! fch4 fixed at a grid value -- gives ch4frac = 0, so the cycle below skips
  ! half the corners and the extra axis costs nothing at runtime.
  palb = 0.0
  do ip = 0, 1
    do ic = 0, 1
      do im = 0, 1
        do it = 0, 1
          do iz = 0, 1
            do ia = 0, 1
              w = ( merge(prefrac, 1.0-prefrac, ip .eq. 1) )                  &
                * ( merge(co2frac, 1.0-co2frac, ic .eq. 1) )                  &
                * ( merge(ch4frac, 1.0-ch4frac, im .eq. 1) )                  &
                * ( merge(tmpfrac, 1.0-tmpfrac, it .eq. 1) )                  &
                * ( merge(zenfrac, 1.0-zenfrac, iz .eq. 1) )                  &
                * ( merge(albfrac, 1.0-albfrac, ia .eq. 1) )
              if ( w .eq. 0.0 ) cycle
              palb = palb + w * palb_table( merge(albhi,alblo,ia .eq. 1),     &
                                            merge(zenhi,zenlo,iz .eq. 1),     &
                                            merge(tmphi,tmplo,it .eq. 1),     &
                                            merge(ch4hi,ch4lo,im .eq. 1),     &
                                            merge(co2hi,co2lo,ic .eq. 1),     &
                                            merge(prehi,prelo,ip .eq. 1) )
            end do
          end do
        end do
      end do
    end do
  end do

  return

end subroutine getPALB

!==================================================================================

subroutine radiation_end

  if ( allocated(olr_table)   ) deallocate( olr_table )
  if ( allocated(palb_table)  ) deallocate( palb_table )
  if ( allocated(prelevels)   ) deallocate( prelevels )
  if ( allocated(fco2levels)  ) deallocate( fco2levels )
  if ( allocated(ch4levels)   ) deallocate( ch4levels )
  if ( allocated(templevels)  ) deallocate( templevels )
  if ( allocated(zenilevels)  ) deallocate( zenilevels )
  if ( allocated(albelevels)  ) deallocate( albelevels )
  if ( allocated(n_eff_upper) ) deallocate( n_eff_upper )
  if ( allocated(n_eff_lower) ) deallocate( n_eff_lower )

end subroutine radiation_end

!==================================================================================

end module radiation_mod
